#!/bin/bash
# shellcheck disable=SC1090
#
# Kind of a generic message generation thing. Hooks in /opt/openslx/system-check/hooks.d
# should write appropriate tags to be displayed to stdout.
# The tags are defined in /opt/openslx/system-check/tags and will be replaced
# by their localized version automatically.

. /opt/openslx/bin/slx-tools

declare -rg root_dir="/opt/openslx/system-check"
declare -rg active_tags_file="/run/hw-warnings.tags"

##
# Read the combined file containing all tags to be displayed, and convert to human readable logfile
render_logfile() {
	local lang_dir lang f dm_warning_file blacklist color do_contact tag
	declare -a tag_with_params

	# Determine which file to put final messages into
	dm_warning_file="$1"
	[ -z "$dm_warning_file" ] && dm_warning_file="$( \
		awk -F'=' '$1 == "greeter-message-file" {print $2}' \
			/etc/lightdm/qt-lightdm-greeter.conf /etc/lightdm/qt-lightdm-greeter.conf.d/* \
			| tail -n 1)"
	[ -z "$dm_warning_file" ] && dm_warning_file="/run/hw-warnings.log"

	# Anything to do at all?
	if [ -e "$dm_warning_file" ] && [ -e "$active_tags_file" ] \
			&& [ "$dm_warning_file" -nt "$active_tags_file" ]; then
		return 0
	fi

	# determine lang. Ignore current environment to make sure we use the system setting
	lang_dir=
	for f in "/etc/default/locale" "/etc/environment"; do
		lang="$( unset LANG LANGUAGE; . "$f" &> /dev/null;
			[ -n "$LANG" ] && echo "${LANG:0:2}" \
			|| echo "${LANGUAGE}" )"
		if [ -d "${root_dir}/lang/${lang}" ]; then
			lang_dir="${root_dir}/lang/${lang}"
			break
		fi
	done
	[ -z "$lang_dir" ] && lang_dir="${root_dir}/lang/en"

	# process all tags in active_tags_file to readable text
	# check in /opt/openslx/messages/{lang,tags}
	blacklist="${root_dir}/blacklist"
	while read -r tag; do
		IFS='|' read -r -a tag_with_params <<< "$tag"
		# blacklisted?
		grep -qFx "${tag_with_params[0]}" "$blacklist" && continue
		# "meta" info?
		unset color contact
		[ -s "${root_dir}/tags/${tag_with_params[0]}" ] && \
			. "${root_dir}/tags/${tag_with_params[0]}"
		print_tag "${color:-000000}" "${tag_with_params[@]}" \
			>> "$dm_warning_file"
		# contact?
		[ -n "$contact" ] && do_contact="yes"
	done < "$active_tags_file"

	# add contact footer if needed
	local support_tag="slx-contact-support"
	if [ -n "$do_contact" ]; then
		[ -s "${root_dir}/tags/${support_tag}" ] && \
			. "${root_dir}/tags/${support_tag}"
		print_tag "${color:-000000}" "${support_tag}" \
			>> "$dm_warning_file"
	fi
}

##
# Call all the hooks to gather relevant tags
generate_messages() {
	local hook_dir file
	hook_dir="${root_dir}/hooks.d"

	# Run hooks that will generate all the warnings
	if [ ! -d "$hook_dir" ]; then
		echo "Missing '$hook_dir' - dev failure?"
		return 1
	fi
	for file in "$hook_dir"/*; do
		[ -s "$file" ] || continue
		[ -x "$file" ] || continue
		"$file" &
	done > "$active_tags_file"
	wait
}

# print_tag <prefix> <file> <vars...>
print_tag() {
	[ "$#" -ge 2 ] || return 1
	local prefix="$1"
	shift
	regex_imatch "$prefix" '^[0-9a-f]{6}$' || prefix="ff00ff"
	# since we fully pass the parsed tag as array, the first param
	# is the tag name, the rest are the variables to substitute %i% with.
	local tag="$1"
	shift
	# get localized message for this tag
	local file="${lang_dir}/${tag}"
	if [ ! -f "$file" ]; then
		# fallback
		echo "000000" "Missing translation for '$tag' in '$lang_dir'."
		return 1
	fi
	while read -r line; do
		line_cur="$line"
		# go over vars and replace %i% with them
		local count=1
		while [ "$#" -ne 0 ]; do
			line_cur="${line_cur//%${count}%/${1}}"
			shift
			(( count++ ))
		done
		echo "$prefix" "$line_cur"
	done < "$file"
}

case "$1" in
--generate)
	shift
	generate_messages "$@"
	;;
--render)
	shift
	render_logfile "$@"
	;;
*)
	echo "Unknown option: $1"
	exit 1
	;;
esac

exit 0
