#!/bin/ash
# Script serves as container script for a systemd-call due to the buggyness of several
# loadkeys-implementations <= kbd (Linux keyboard tools) 1.15.3.
# This bug can be detected through failure of the command pipe 'dumpkeys|loadkeys' yielding
# the message "unknown keysym 'compose'.

loadkeys  /opt/openslx/keymaps/qwertz_de_CH-latin1.map		# insert a keymap without compose lines
ERR=$?

# if at this point the second keymap insertion failed we pass the errorlevel to
# systemd - we cannot do more at this point.
exit $ERR

