#!/bin/bash
# ^ sourced!

export PATH=$PATH:/opt/openslx/sbin:/opt/openslx/bin

command -v slxbrowser || return 0

OPTS=()

# Ignore SSL errors
[ -n "$SLX_BROWSER_INSECURE" ] && [ "$SLX_BROWSER_INSECURE" -gt 0 ] && OPTS+=("--insecure")
# On inactivity, reload every X seconds
[ -n "$SLX_BROWSER_RELOAD_SECS" ] && [ "$SLX_BROWSER_RELOAD_SECS" -gt 0 ] && OPTS+=("--reload-interval" "$SLX_BROWSER_RELOAD_SECS")
# If set, is a space separated list of URLs or hosts
if [ -n "$SLX_BROWSER_URLLIST" ]; then
	# Turn into file with one entry per line
	LIST=$(mktemp)
	echo "$SLX_BROWSER_URLLIST" | sed -r 's/\s+/\n/g' > "$LIST"
	# Is it a whitelist or blacklist
	if [ -n "$SLX_BROWSER_IS_WHITELIST" ] && [ "$SLX_BROWSER_IS_WHITELIST" -gt 0 ]; then
		OPTS+=("--whitelist" "$LIST")
	else
		OPTS+=("--blacklist" "$LIST")
	fi
	# Async, clean up file after slxbrowser read it
	( sleep 5; rm -f -- "$LIST" ) &
fi

if [ -z "${SLX_AUTOLOGIN%OFF}" ]; then
	OPTS+=("--maximized")
else
	OPTS+=("--fullscreen")
fi

# HACK: give whatever enough time to whatever it does properly
sleep 1

exec slxbrowser "${OPTS[@]}" "$SLX_BROWSER_URL"
