#!/bin/ash

# Allow PVS ports
# Control connection: server incoming, client outgoing
iptables -I ipt-helper-INPUT 1 -i br0 -p tcp --dport 5194 -j ACCEPT
iptables -I ipt-helper-OUTPUT 1 -o br0 -p tcp --dport 5194 -j ACCEPT
# UDP discovery
# pvsmgr: allow incoming discovery (broadcast)
iptables -I ipt-helper-INPUT 1 -i br0 -p udp --dport 3492 -j ACCEPT
# pvsmgr: allow outgoing discovery reply (unicast)
iptables -I ipt-helper-OUTPUT 1 -o br0 -p udp --sport 3492 -j ACCEPT
# pvsclient: allow outgoing discovery (broadcast)
iptables -I ipt-helper-OUTPUT 1 -o br0 -p udp --dport 3492 -j ACCEPT
# pvsclient: allow incoming discovery reply (unicast)
iptables -I ipt-helper-INPUT 1 -i br0 -p udp --sport 3492 -j ACCEPT
# VNC connection - incoming and outgoing - small range as we use -autoport
iptables -I ipt-helper-INPUT 1 -i br0 -p tcp --dport 54112:54122 -j ACCEPT
iptables -I ipt-helper-OUTPUT 1 -o br0 -p tcp --dport 54112:54122 -j ACCEPT
