#!/bin/ash

wfile="/run/user/$(id -u)/virt-viewer-wins"

if [ "$1" = "pre" ]; then
	# Find all virt-viewer windows currently visible
	WINDOWS=$(
		xdotool search --onlyvisible --class virt-viewer
		xdotool search --onlyvisible --class remote-viewer
	)
	[ -z "$WINDOWS" ] && exit 0
	for window in $WINDOWS; do
		xdotool windowminimize $window
		echo "$window" >> "$wfile" # Remember for later
	done
	# move mouse pointer around to avoid some problems with ghost clicks
	# also this resets the idle time durr hurr
	xdotool mousemove 0 0
	usleep 10000
	xdotool mousemove --polar 0 0
	usleep 10000
	xdotool key "ctrl+alt+shift+super"
	usleep 10000
fi

if [ "$1" = "post" ]; then
	(
	# let's restore virt-viewer
	sleep 1
	WINDOWS=$(sort -u "$wfile")
	for window in $WINDOWS; do
		xdotool windowmap $window
	done
	) &
fi

exit 0
