#!/bin/ash

[ -z "$SLX_KCL_SERVERS" ] && . /opt/openslx/config

# HACK: Don't interfere when we're in remote access mode
[ -n "$SLX_REMOTE_VNC" ] && return 0
# Also don't interfere if we requested a minimal gui
. /opt/openslx/bin/slx-tools
is_on "$SLX_MINIMAL_GUI" && return 0

if [ -z "$SLX_FORCE_RESOLUTION" ]; then
	# Nothing set, normal operation
	/opt/openslx/bin/beamergui -a
	# Detach
	/bin/bash <<HERE
	{
		ulimit -c unlimited
		cd /tmp/
		/opt/openslx/bin/beamergui -b &
	} &
HERE
elif [ -z "$SLX_RESOLUTION_MAPPING" ]; then
	# Forced resolution only
	/opt/openslx/bin/beamergui --resolutions "$SLX_FORCE_RESOLUTION"
else
	# Forced resolution and mapping
	/opt/openslx/bin/beamergui --resolutions "$SLX_FORCE_RESOLUTION" --mapping "$SLX_RESOLUTION_MAPPING"
fi

true

