#!/bin/ash
# -----------------------------------------------------------------------------
#
# Copyright (c) 2017..2018 bwLehrpool-Projektteam
#
# This program/file is free software distributed under the GPL version 2.
# See https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
#
# If you have any feedback please consult https://bwlehrpool.de and
# send your feedback to support@bwlehrpool.de.
#
# General information about bwLehrpool can be found at https://bwlehrpool.de
#
# -----------------------------------------------------------------------------
# systemd-qemukvm_env
#    - This is the preparation script for the configuration of Linux Qemu/KVM.
################################################################################

# lazy load all kvm related modules
modprobe kvm
modprobe kvm_amd
modprobe kvm_intel

if [ ! -e /dev/kvm ]; then
	slxlog "qemukvm-modules" "/dev/kvm not found! Missing kvm kernel module(s)?"
	exit 1
fi

