#!/bin/ash
# -----------------------------------------------------------------------------
# Copyright (c) 2017 - OpenSLX GmbH
#
# This program/file is free software distributed under the GPL version 2.
# See http://openslx.org/COPYING
#
# If you have any feedback please consult http://openslx.org/feedback and
# send your feedback to feedback@openslx.org
#
# General information about OpenSLX can be found at http://openslx.org
# -----------------------------------------------------------------------------
# systemd-qemukvm_env
#    - This is the preparation script for the configuration of Linux Qemu/KVM.
################################################################################

# lazy load all kvm related modules
modprobe kvm
modprobe kvm_amd
modprobe kvm_intel

if [ ! -e /dev/kvm ]; then
	slxlog "qemukvm-modules" "/dev/kvm not found! Missing kvm kernel module(s)?"
	exit 1
fi

