#!/bin/ash

export PATH="$PATH:/opt/openslx/sbin:/opt/openslx/bin"

ERRLOG="/run/dnbd3-proxy.err"

if [ -s "$ERRLOG" ]; then
	exec $(which dnbd3-server) -n --errormsg "$(cat "$ERRLOG")" -c /etc/dnbd3-server
fi

exec $(which dnbd3-server) -n -c /etc/dnbd3-server

exit 1

