#!/bin/ash
#
# /etc/X11/Xreset
#
# Xreset - run as root after session exits
#

# Only run this if a session was actually started, as lightdm also calls
# this script on every failed login attempt
[ -e "/run/openslx/ldm-session-$DISPLAY" ] || exit 0
rm -f -- "/run/openslx/ldm-session-$DISPLAY"

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/openslx/sbin:/opt/openslx/bin"

PROGNAME=Xreset
SYSSESSIONDIR=/etc/X11/Xreset.d

if [ ! -d "$SYSSESSIONDIR" ]; then
  # Nothing to do, exiting
  exit 0
fi

for SESSIONFILE in $SYSSESSIONDIR/*; do
	. "$SESSIONFILE" || slxlog "xreset" "Xreset: Could not source $SESSIONFILE." "$SESSIONFILE" 
done

exit 0

