#!/bin/ash

. /opt/openslx/config

[ -z "$SLX_BROWSER_URL" ] && exit 1

xset s off
xset -dpms

openbox &

[ -n "$SLX_BROWSER_INSECURE" ] && SLX_BROWSER_INSECURE="--insecure"

exec slxbrowser $SLX_BROWSER_INSECURE --fullscreen "$SLX_BROWSER_URL"

