#!/bin/ash
#
# Simple "preload" by just reading the directory /usr/lib/chromium-browser 
# Tested the variation loading just the linked libraries, but it does
# not bring the same startup acceleration than this trivial method...

. /opt/openslx/config

if [ "${SLX_BROWSER//chromium/}" != "$SLX_BROWSER" ]; then
	(
	dd if=/usr/lib/chromium-browser/chromium-browser of=/dev/null &> /dev/null &
	) &
fi
