#!/bin/ash
# This file is executed in /opt/openslx/scripts/systemd-generate_warnings
# If a first parameter is given, we write to that file instead of stdout.

. /opt/openslx/config
. /run/openslx/hwinfo

if [ -n "$1" ]; then
	exec >> "$1"
fi

if lspci -nk | grep -q 'Kernel driver in use: nouveau'; then
	echo 'slx-gfx-nouveau'
fi
