#!/bin/ash

. /opt/openslx/config

[ -z "$SLX_PROXY_MODE" ] && exit 0
[ "$SLX_PROXY_MODE" = "off" ] && exit 0
[ -z "$SLX_PROXY_IP" ] && exit 0

iptables -A OUTPUT -d "$SLX_PROXY_IP" -p tcp --dport "$SLX_PROXY_PORT" -j ACCEPT
