#!/bin/ash

# check if kernel sees a preloaded kernel for kexec
if which kexec 2>/dev/null && [ "x$(cat /sys/kernel/kexec_loaded)" = "x1" ]; then
	kexec -e
fi

# enable sysrq and trigger reboot
echo 1 > /proc/sys/kernel/sysrq
echo b > /proc/sysrq-trigger

# TODO start fbsplash or something
