#!/bin/ash

rm -rf -- "/run/iptables-reloader.cache" "/run/iptables-reloader.lock"

modprobe br_netfilter

/opt/openslx/iptables/iptables-reloader-worker
exec /opt/openslx/sbin/inotifyd /opt/openslx/iptables/iptables-reloader-worker /opt/openslx/iptables/rules.d:cndmy

