#!/bin/bash

NET_IF="$1"
NET_IP="$(ip addr show dev "${NET_IF}" | grep -m1 '^\s*inet ' | awk -F " " '{print $2}' | awk -F "/" '{print $1}')"

UDHCPC_OPTS=""
if [ -n "$NET_IP" ]; then
	UDHCPC_OPTS="$UDHCPC_OPTS -r $NET_IP"
fi

UID=$(dmidecode -s system-uuid | sed -r 's/^(..)(..)(..)(..)-(..)(..)-(..)(..)-(....)-/00\4\3\2\1\6\5\8\7\9/')
if [ "${#UID}" = 34 ]; then
	echo "Using SMBIOS UID for DHCP"
	UDHCPC_OPTS="$UDHCPC_OPTS -x 0x3d:$UID"
fi

mkdir -p /run/udhcpc || echo "Could not create '/run/udhcpc'."

/opt/openslx/sbin/udhcpc $UDHCPC_OPTS -O domain -O nissrv -O nisdomain -O wpad -O search -O wins -t 8 -s /opt/openslx/scripts/udhcpc-openslx -i "$NET_IF" -p "/run/udhcpc/udhcpc.$NET_IF.pid"
RET=$?

if [ "$RET" != 0 ]; then
	slxlog "udhcpc" "Could not run 'udhcpc ${UDHCPC_OPTS}' on ${NET_IF}."
fi

exit "$RET"

