#!/bin/ash

LIST="$(< /etc/shadow awk -F: '{printf $1 ","}')"
sed -i "s/^filter_users.*\$/filter_users = ${LIST%,}/g" /etc/sssd/sssd.conf

LIST="$(< /etc/group awk -F: '{printf $1 ","}')"
sed -i "s/^filter_groups.*\$/filter_groups = ${LIST%,}/g" /etc/sssd/sssd.conf

exit 0

