#!/bin/ash

export PATH=$PATH:/opt/openslx/sbin:/opt/openslx/bin

if ! ( lsmod | grep -q dnbd3 ||  modprobe dnbd3 ); then
	slxlog "dnbd3-kernel" "Error loading dnbd3 client kernel module"
	exit 1
fi

[ -e "/dev/dnbd0" ] || exit 1
for i in /dev/dnbd*; do
	echo 8192 > "/sys/block/dnbd${i#/dev/dnbd}/queue/nr_requests"
done

exec dnbd3-client --daemon
slxlog "dnbd3-daemon" "Error launching dnbd3-client daemon"
exit 1

