#!/bin/ash
#
# Simple "preload" by just reading the directory /usr/lib/chromium-browser 
# Tested the variation loading just the linked libraries, but it does
# not bring the same startup acceleration than this trivial method...

. /opt/openslx/config

if [ "${SLX_BROWSER//firefox/}" != "$SLX_BROWSER" ]; then
	echo "Preloading Firefox files"
	for dir in /lib/firefox /usr/lib/firefox /lib/firefox-esr /usr/lib/firefox-esr; do
		[ -d "$dir" ] || continue
		ok=
		for i in firefox firefox-esr libxul.so omni.ja; do
			[ -s "$dir/$i" ] || continue
			ok=1
			cat "$dir/$i" &> /dev/null &
		done
		if [ -n "$ok" ]; then
			wait
			echo "Finished preloading Firefox"
			break
		fi
	done &
fi
