#!/bin/ash
#
#	Script to be called by systemd
#
#	Downloads and appends addons per sqfs/aufs.
#
######################################################################################
#
#	Two modes for this script:
#		- without any arguments, it will just go through the list of addons to
#		  setup as given through the OpenSLX configuration file
#		- with an argument, it will setup the addon given as $1
#
#
######################################################################################

# read global OpenSLX config
. /opt/openslx/config || { echo "Could not source config!"; exit 23; }

# source functions.inc for the download function
. /opt/openslx/inc/functions || { echo "/opt/openslx/inc/functions not found!"; exit 1337; }

# quick fix for the missing FUTURE_ROOT needed by /opt/openslx/etc/functions.inc
export FUTURE_ROOT="/"

# read openslx config, especially servers given by SLX_KCL_SERVERS and SLX_CONFIG_SERVERS
if [ -z "${SLX_CONFIG_SERVERS}" ]; then
	echo "SLX_CONFIG_SERVERS is not set in /opt/openslx/config. Will only try the base servers from the cmdline."
	#[ -z "${SLX_KCL_SERVERS}" ] && SLX_KCL_SERVERS=$(read_from_cmdline "slxsrv")
fi

# read base slx servers from cmdline
DOWNLOAD_DEST="/run/addons"
mkdir -p "$DOWNLOAD_DEST" || { echo "Failed to create $DOWNLOAD_DEST"; exit 1; }

######################################################################################
#
#				DOWNLOAD ALL ADDONS
#
if [ $# -eq 0 ]; then
	if [ -z "${SLX_ADDONS}" ]; then
		echo "No addons configured. Nothing to do :-)."
	else
		for ADDON in ${SLX_ADDONS}; do
			# Use bg not --no-block so we can wait below
			systemctl start "download-slx-addon@$ADDON.service" &
		done
		echo "Waiting for addon downloads to finish"
		wait
	fi
	[ -n "$SLX_SPLASH" ] && splashtool --icon "/opt/openslx/icons/active/??-puzzle.ppm"
	exit 0
fi
##
# DOWNLOAD SINGLE ADDON
if [ $# -eq 1 ]; then
	ADDON="$1"
	ADDON_TARGET_PATH="${DOWNLOAD_DEST}/$(basename "$ADDON").sqfs"
	if [ -f "${SLX_BASE_PATH}/${ADDON}.sqfs" ]; then
		echo "Already downloaded, doing nothing"
		exit 0
	fi
	# XXX HACK
	# Select proper VMware version
	FILE="$ADDON"
	if [ "$ADDON" = "vmware" ]; then
		# check with the helper
		version="$(vmware-get-supported-version)"
		FILE="vmware$version"
		echo "Deciding to download $FILE instead of $ADDON after checking CPU"
	fi
	# XXX
	if ! download "${SLX_BASE_PATH}/${FILE}.sqfs" "${ADDON_TARGET_PATH}"; then
		slxlog --echo "addon-download" "Download of '${HTTP_BASE_PATH}/${ADDON}.sqfs' failed."
		exit 1
	fi
fi

[ $# -gt 1 ] && { echo "$0 needs 0 or 1 arguments! $# given."; exit 1; }

exit 0

