#!/bin/bash

if lsmod | grep -q '^nvidia\s'; then
	# nvidia kernel module was loaded in stage31 - download libs
	version=$( cat /sys/module/nvidia/version )
	if [ -n "$version" ]; then
		echo "Proprietary nvidia kernel drivers v$version loaded - fetch user space libs"
		/opt/openslx/scripts/systemd-download_slx_addons "nvidia-libs@$version"
		/opt/openslx/scripts/systemd-setup_slx_addons "nvidia-libs@$version" || exit 1
	fi
fi

exit 0
