#!/bin/ash
# -----------------------------------------------------------------------------
#
# Copyright (c) 2013..2026 bwLehrpool-Projektteam
#
# This program/file is free software distributed under the GPL version 2.
# See https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
#
# If you have any feedback please consult https://bwlehrpool.de and
# send your feedback to support@bwlehrpool.de.
#
# General information about bwLehrpool can be found at https://bwlehrpool.de
#
# -----------------------------------------------------------------------------
#
# Local hard disk autodetection script for OpenSLX linux stateless clients,
# detecting swap and special partitions

#############################################################################

# Add zram swap

read_swap_config() {
	# Determine non-zram swap size
	disk_swap_kb="$( gawk 'BEGIN{a=0} $1 !~ /^\/zram/ && $1 !~ /^\/dev\/zram/ {a+= $3} END{print a}' /proc/swaps )"
	# total swap
	total_swap_kb="$( gawk 'BEGIN{a=0} $1 ~ /^\// {a+= $3} END{print a}' /proc/swaps )"
}

configure_zswap() {
	# Enable zswap only if we're not using any zram as swap, as that would be redundant
	if [ "$total_swap_kb" = "$disk_swap_kb" ]; then
		modprobe zswap
		echo 1 > /sys/module/zswap/parameters/enabled
	else
		echo 0 > /sys/module/zswap/parameters/enabled
		# Increase min free memory so we have enough mem available when trying to move
		# something to zram swap. We want 1%, or at least 64MiB
		local current_min_free_kb want_min_free_kb
		current_min_free_kb=$(cat "/proc/sys/vm/min_free_kbytes")
		want_min_free_kb=$(( total_mem_kb / 100 ))
		[ "$want_min_free_kb" -gt 65536 ] || want_min_free_kb=65536 # minimum 64M
		[ "$want_min_free_kb" -lt 524800 ] || want_min_free_kb=524800 # maximum 512M
		if [ "$current_min_free_kb" -lt "$want_min_free_kb" ]; then
			echo "$want_min_free_kb" > "/proc/sys/vm/min_free_kbytes"
		fi
	fi
}

read_swap_config
# If we already have >= 2GB swap, do nothing
if [ "$total_swap_kb" -ge 2048000 ]; then # ~2 GB (in KB)
	echo "Not setting up zram swap as swap partition is in use."
	configure_zswap
	exit 0
fi

if [ -e "/sys/class/zram-control/hot_add" ]; then
	: # nothing to do, loaded and hot_add available
elif ! modprobe zram "num_devices=2"; then # one spare for whatever
	echo "ERROR: Could not load zram module"
	exit 1
fi

# Go for it

make_swap () {
	if ! [ $# -eq 2 ]; then
		echo "make_swap: Wrong parameter count $#"
		return 1
	fi
	local zram_size_bytes="$1"
	local DEV="$2"
	echo "$zram_size_bytes" > "/sys/block/zram${DEV}/disksize" || return 1
	(
		mkswap "/dev/zram${DEV}"
		swapon "/dev/zram${DEV}" -p 1000 # high priority (in case we have hdd swap 0x82, prefer zram)
	) &
}

total_mem_kb=$( awk '{ if ($1 == "MemTotal:") { print $2; exit } }' /proc/meminfo )
use_kb=$(( total_mem_kb / 2 - disk_swap_kb ))
if ! [ "$use_kb" -gt "$(( total_mem_kb / 8 ))" ]; then # catch NaN through negation
	use_kb=$(( total_mem_kb / 8 ))
fi
echo "Have $total_mem_kb kb mem, create $use_kb kb zram swap."
zram_size_bytes=$(( use_kb * 1024 ))
DEVS=1
DEV=0
NUM=0
FAILS=0
while [ "$NUM" -lt "$DEVS" ]; do
	if [ -e "/sys/block/zram${DEV}" ]; then
		if ! [ -e "/sys/block/zram${DEV}/initstate" ] || [ "$(cat "/sys/block/zram${DEV}/initstate")" = 0 ]; then
			if make_swap "$zram_size_bytes" "$DEV"; then
				NUM=$(( NUM + 1 ))
			fi
		fi
		DEV=$(( DEV + 1 ))
	elif [ -e "/sys/class/zram-control/hot_add" ]; then
		DEV=$(cat /sys/class/zram-control/hot_add)
		if [ -z "$DEV" ]; then
			echo "ERROR: Cannot hot_add another zram device"
			break
		fi
		if make_swap "$zram_size_bytes" "$DEV"; then
			NUM=$(( NUM + 1 ))
		else
			FAILS=$(( FAILS + 1 ))
			if [ "$FAILS" -gt 4 ]; then
				echo "ERROR: Could not swap on hot added device -- giving up"
				break
			fi
		fi
		DEV=$(( DEV + 1 ))
	else
		echo "ERROR: Cannot add another zram device: No hot_add support"
		break
	fi
done

# Wait, so we don't trigger swap.target too early
wait

# Finally, enable zswap if we created at least one zram device
read_swap_config
configure_zswap

exit 0

