#!/bin/ash

disable_tty_switch() {
	cat <<EOF > /etc/X11/xorg.conf.d/50-no-tty.conf
Section "ServerFlags"
	Option "DontVTSwitch" "true"
EndSection
EOF
}

disable_openbox_menu() {
	[ ! -e "/etc/xdg/openbox/rc.xml.safe" ] && \
		echo "No rc.xml.safe template found." && return 1
	cp "/etc/xdg/openbox/rc.xml" "/root/rc.xml.unsafe"
	cp "/etc/xdg/openbox/rc.xml.safe" "/etc/xdg/openbox/rc.xml"
}

disable_magic_keys() {
	echo 0 > /proc/sys/kernel/sysrq
}

disable_screen_standby() {
	xset s off -dpms
}

change_loginscreen() {
	local CF="/etc/lightdm/qt-lightdm-greeter.conf"
	sed -r -i '/^greeter-background/d;s:(^greeter-banner-image=).*$:\1/opt/openslx/lightdm/bwlp-banner-exam.svg:' "$CF"
	echo "greeter-background-gradient=FFB22C FFB22C" >> "$CF"
}

systemd_config() {
	# Disable ctrl-alt-delete
	rm -- "/usr/lib/systemd/system/ctrl-alt-del.target"
	# No idleaction
	rm -- "/etc/cron.d/openslx-idleaction"
	# Ignore everything but power button, no VTs
	cat > "${FUTURE_ROOT}/etc/systemd/logind.conf" <<EOF
[Login]
NAutoVTs=0
ReserveVT=0
KillUserProcesses=no
HandlePowerKey=poweroff
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
IdleAction=ignore
EOF
	# reload
	systemctl daemon-reload
	systemctl restart systemd-logind
}

ssh_banner() {
	# Visual: ssh banner
	echo "+ - - - - KLAUSURMODUS AKTIV - - - - +" >> "/etc/issue.net"
	echo "++++++++++++++++++++++++++++++++++++++" >> "/etc/issue.net"
}


disable_tty_switch
disable_openbox_menu
disable_magic_keys
disable_screen_standby
change_loginscreen
systemd_config
ssh_banner

exit 0

