#!/bin/ash
# -----------------------------------------------------------------------------
# Copyright (c) 2007..2013 - RZ Uni FR
# Copyright (c) 2007..2013 - OpenSLX GmbH
#
# This program is free software distributed under the GPL version 2.
# See http://openslx.org/COPYING
#
# If you have any feedback please consult http://openslx.org/feedback and
# send your suggestions, praise, or complaints to feedback@openslx.org
#
# General information about OpenSLX can be found at http://openslx.org/
# -----------------------------------------------------------------------------
# systemd-vbox_env
#    - This is the preparation script for the configuration of VirtualBox.
################################################################################

export PATH="$PATH":/opt/openslx/bin:/opt/openslx/sbin

## sanity checks
VBOX_BASE_DIR="/usr/lib/virtualbox"
VBOX_KMOD_DIR="/lib/modules/vbox"

# VBoxManage should be under /usr/lib/virtualbox
if ! [ -d "${VBOX_BASE_DIR}" -o -x "${VBOX_BASE_DIR}/VBoxManage" -o -d "${VBOX_KMOD_DIR}" ]; then
	echo "Failed to find VirtualBox installation at expected paths."
	exit 1
fi

# reload udev rules since aufs'ing the layer on top do not
# trigger its inotify watch
udevadm control --reload

# create required standard directories
mkdir -p "/tmp/virt/virtualbox" -m 1777

# load required Vbox modules
cd "${VBOX_KMOD_DIR}"
for MOD in *; do
  insmod "${MOD}" || slxlog "vbox-setup" "Loading of ${MOD} failed."
done

# check/create vboxusers group
getent group vboxusers || addgroup -S vboxusers

chown root:vboxusers /dev/vboxdrv
chmod 666 /dev/vboxdrv
chown root:vboxusers /dev/vboxdrvu
chmod 666 /dev/vboxdrvu

# pretty dumb you can just create host-only interfaces,
# but not assign a specific name/number
VBOXMANAGE="${VBOX_BASE_DIR}/VBoxManage"
${VBOXMANAGE} hostonlyif create
ip link set dev vboxnet0 up
brctl addif br0 vboxnet0

${VBOXMANAGE} hostonlyif create 
ip link set dev vboxnet1 up
brctl addif nat1 vboxnet1

${VBOXMANAGE} hostonlyif create
ip link set dev vboxnet2 up
brctl addif vsw2 vboxnet2

true
