#!/bin/ash
# -----------------------------------------------------------------------------
#
# Copyright (c) 2007..2018 bwLehrpool-Projektteam
#
# This program/file is free software distributed under the GPL version 2.
# See https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
#
# If you have any feedback please consult https://bwlehrpool.de and
# send your feedback to bwlehrpool@hs-offenburg.de.
#
# General information about bwLehrpool can be found at https://bwlehrpool.de
#
# -----------------------------------------------------------------------------
# systemd-vbox_env
#    - This is the preparation script for the configuration of VirtualBox.
################################################################################

export PATH="$PATH":/opt/openslx/bin:/opt/openslx/sbin

## sanity checks
VBOX_BASE_DIR="/usr/lib/virtualbox"
VBOX_KMOD_DIR="/lib/modules/vbox"
VBOX_MANAGE="${VBOX_BASE_DIR}/VBoxManage"

# Runtime critical checks first
# VBoxManage should be under /usr/lib/virtualbox
if ! [ -d "${VBOX_BASE_DIR}" -o -x "${VBOX_MANAGE}" -o -d "${VBOX_KMOD_DIR}" ]; then
	echo "Failed to find VirtualBox installation at expected paths."
	exit 1
fi

# load vbox kernel modules
cd "${VBOX_KMOD_DIR}"
for MOD in *; do
	if ! insmod "${MOD}"; then
		slxlog "vbox-setup" "Loading of ${MOD} failed."
		exit 1
	fi
done

# check/create vboxusers group
getent group vboxusers || addgroup -S vboxusers

# set their permissions
chown root:vboxusers /dev/vboxdrv
chmod 666 /dev/vboxdrv
chown root:vboxusers /dev/vboxdrvu
chmod 666 /dev/vboxdrvu

# create required standard directories
mkdir -p "/tmp/virt/virtualbox" -m 1777

# reload udev rules since aufs'ing the layer on top do not trigger its inotify watch
udevadm control --reload

# pretty dumb you can just create host-only interfaces,
# but not assign a specific name/number
${VBOX_MANAGE} hostonlyif create
ip link set dev vboxnet0 up
brctl addif br0 vboxnet0

${VBOX_MANAGE} hostonlyif create
ip link set dev vboxnet1 up
brctl addif nat1 vboxnet1

${VBOX_MANAGE} hostonlyif create
ip link set dev vboxnet2 up
brctl addif vsw2 vboxnet2

exit 0
