#!/bin/ash

[ -z "$SLX_PXE_CLIENT_IP" ] && . /opt/openslx/config

if [ -n "$SLX_PREFERRED_SOUND_OUTPUT" ] \
		&& [ "${SLX_PREFERRED_SOUND_OUTPUT}" != "SOUNDCARD" ]; then
	(
		sleep 5
		/opt/openslx/bin/pavucontrol-slx -o "$SLX_PREFERRED_SOUND_OUTPUT"
	) &
fi
true
