#!/bin/ash

. /opt/openslx/config

[ -z "${SLX_DNBD3_SERVERS}${SLX_DNBD3_FALLBACK}" ] && exit 0

. /opt/openslx/bin/slx-tools

for ip in $SLX_DNBD3_SERVERS $SLX_DNBD3_FALLBACK; do
	net_split "$ip" 5003 || continue
	iptables -A OUTPUT -d "$nethost" -p tcp --dport "$netport" -j ACCEPT
done

exit 0
