#!/bin/ash

if which xscreensaver; then
	DPMS=False
	AUTOLOCK=True
	secsToTime() {
		local NUM SECS MINS HRS
		NUM="$1"
		SECS=0$(( NUM % 60 ))
		MINS=0$(( ( NUM / 60 ) % 60 ))
		HRS=0$(( ( NUM / 3600 ) % 60 ))
		echo "${HRS:$(( ${#HRS} - 2 )):2}:${MINS:$(( ${#MINS} - 2 )):2}:${SECS:$(( ${#SECS} - 2 )):2}"
	}
	[ -z "$UID" ] && UID=$(id -u)
	[ -z "$HOME" ] && HOME="$(getent passwd "$UID" | head -n 1 | awk -F ':' '{print $6}')"
	. /opt/openslx/config
	SBY="${SLX_SCREEN_STANDBY_TIMEOUT}"
	if [ -n "${SLX_EXAM}" ]; then
		SLX_SCREEN_SAVER_TIMEOUT=0
		SLX_SCREEN_SAVER_GRACE_TIME=
		AUTOLOCK=False
		SBY=0
	elif [ -z "$SBY" ]; then
		SBY=0
	elif [ "$SBY" -gt 0 ] && [ "$SBY" -lt 60 ]; then
		SBY=60
	elif ! [ "$SBY" -ge 0 ]; then # isNumeric?
		SBY=0
	fi
	# Create config value for standby timeout
	if [ "$SBY" -gt 0 ]; then
		DPMS=True
		STANDBY="$( secsToTime "$(( SBY + 60 ))" )"
	else
		STANDBY="99:00:00"
	fi
	# Explicit screen saver timeout set
	if [ "$SLX_SCREEN_SAVER_TIMEOUT" -gt 0 ]; then
		TIMEOUT="$( secsToTime "$(( SLX_SCREEN_SAVER_TIMEOUT + 30 ))" )"
	else
		TIMEOUT="99:00:00"
	fi
	if [ -z "$SLX_SCREEN_SAVER_GRACE_TIME" ]; then
		GRACE="99:00:00"
		AUTOLOCK=False
	else
		GRACE="$( secsToTime "$SLX_SCREEN_SAVER_GRACE_TIME" )"
	fi
	if ! [ -s "$HOME/.xscreensaver" ]; then
		cat > "$HOME/.xscreensaver" <<EOF
mode:         one
cycle:        99:00:00
timeout:      $TIMEOUT
lock:         $AUTOLOCK
lockTimeout:  $GRACE
fade:         False
unfade:       False
dpmsEnabled:  $DPMS
dpmsStandby:  $STANDBY
dpmsSuspend:  $STANDBY
dpmsOff:      $STANDBY
dpmsFullThrottle: True
newLoginCommand:
externalUngrabCommand: /opt/openslx/xscreensaver/ungrab
programs:     /opt/openslx/bin/bwlp-screensaver
selected:     0
EOF
	fi
	xscreensaver -no-splash &
fi

true

