#!/bin/ash

SOURCEPATH="/opt/openslx/vmchooser/sessionstart.d"

if [ -d "$SOURCEPATH" ]; then
	for file in $SOURCEPATH/*; do
		"$file" || slxlog "vmchooser-sessionstart" "Could not source $file at session start!" "$file"
	done
fi

exit 0

