#!/bin/ash 
# ^ sourced

# This is required for Mesa 20.0+ for now. Starting from this version,
# the new "Iris" OpenGL driver has been made default for intel Gen8
# and newer, which unfortunately completely breaks 3D acceleration with
# VMware 15.5.6 (as of 2020-08-04 with Mesa 20.0 + Ubuntu 20.04 as base)

export MESA_LOADER_DRIVER_OVERRIDE=i965

