#!/bin/ash

# Give it some time, in case starting the session fails.
# In that case, vmchooser will send us a SIGTERM, which will
# hopefully happen within one second, so we wont't execute
# all the sessionstart hooks.
sleep 1

SOURCEPATH="/opt/openslx/vmchooser/sessionstart.d"

if [ -d "$SOURCEPATH" ]; then
	for file in $SOURCEPATH/*; do
		"$file"
		RET=$?
		if [ "$RET" != 0 ]; then
			param="$file"
			[ "$(head -n 1 "$file" | cut -b 1)" != "#" ] && param=
			slxlog "vmchooser-sessionstart" "$file returned $RET at session start!" "$param"
		fi
	done
fi

exit 0

