#!/bin/ash

AUTH_KEYS_DIR="/root/.ssh/authorized_keys.d/"
AUTH_KEYS_FILE="/root/.ssh/authorized_keys"

# do we even have the directory?
[ ! -d "$AUTH_KEYS_DIR" ] && echo "No such directory: $AUTH_KEYS_DIR" && exit 0

mkdir -m 700 $(dirname "$AUTH_KEYS_FILE") 2>/dev/null
TMP=$(mktemp)

[ -s "$AUTH_KEYS_FILE" ] && cat "$AUTH_KEYS_FILE" >> "$TMP"

# ok, lets cat them in the real file
for KEY in "$AUTH_KEYS_DIR"/* ; do
	grep -E '(^#|\bssh-.*\sAAA)' "$KEY" >> "$TMP"
done

sort -u "$TMP" > "$AUTH_KEYS_FILE" || cp -f "$TMP" "$AUTH_KEYS_FILE"

rm -f -- "$TMP"

# all done, all good
exit 0
