#!/bin/ash

. /opt/openslx/config

[ -n "$SLX_REMOTE_VNC" ] || exit 0 # Nothing to do

ln -nfs /opt/openslx/remote-access/xorg.conf /etc/X11/xorg.conf.d/16-remote-access.conf

cat > /etc/lightdm/qt-lightdm-greeter.conf.d/13-loginrpc.conf <<END
[General]
rpc-port = 7551
END
