#!/bin/ash
# -----------------------------------------------------------------------------
#
# Copyright (c) 2016..2018 bwLehrpool-Projektteam
#
# This program/file is free software distributed under the GPL version 2.
# See https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
#
# If you have any feedback please consult https://bwlehrpool.de and
# send your feedback to bwlehrpool@hs-offenburg.de.
#
# General information about bwLehrpool can be found at https://bwlehrpool.de
#
# -----------------------------------------------------------------------------
# systemd-vbox_env
#    - This is the preparation script for the configuration of VirtualBox.
################################################################################

export PATH="$PATH":/opt/openslx/bin:/opt/openslx/sbin
VBOX_CONF_DIR=/opt/openslx/etc/vbox
VBOXMANAGE=$(which vboxmanage)

# create required standard directories
mkdir -p "/tmp/virt/virtualbox" -m 1777

# load required Vbox modules
for module in vboxdrv.ko vboxnetadp.ko vboxnetflt.ko vboxpci.ko ; do
  insmod /lib/modules/vbox/${module} || slxlog "vbox-systemd" "Loading of ${module} failed."
done

# unload modules if proper systemd shutdown is provided
#unload_modules () { 
#	rmmod vboxpci vboxnetflt vboxnetadp vboxdrv
#}

# Should be done by udev rule - no mknod needed.
# mknod -m 0660 /dev/vboxdrv c 10 59

chown root:vboxusers /dev/vboxdrv
chmod 666 /dev/vboxdrv
chown root:vboxusers /dev/vboxdrvu
chmod 666 /dev/vboxdrvu
chown root:vboxusers /dev/vboxusb
chmod 755 /dev/vboxusb

# pretty dumb you can just create host-only interfaces, but not assign a specific
# name/number
vboxmanage hostonlyif create
ip link set dev vboxnet0 up
brctl addif br0 vboxnet0
vboxmanage hostonlyif create 
ip link set dev vboxnet1 up
brctl addif nat1 vboxnet1
vboxmanage hostonlyif create
ip link set dev vboxnet2 up
brctl addif vsw2 vboxnet2
