#!/bin/ash

if which xscreensaver; then
	AUTOLOCK=True
	secsToTime() {
		local NUM SECS MINS HRS
		NUM="$1"
		SECS=0$(( NUM % 60 ))
		MINS=0$(( ( NUM / 60 ) % 60 ))
		HRS=0$(( ( NUM / 3600 ) % 60 ))
		echo "${HRS:$(( ${#HRS} - 2 )):2}:${MINS:$(( ${#MINS} - 2 )):2}:${SECS:$(( ${#SECS} - 2 )):2}"
	}
	[ -z "$UID" ] && UID=$(id -u)
	[ -z "$HOME" ] && HOME="$(getent passwd "$UID" | head -n 1 | awk -F ':' '{print $6}')"
	. /opt/openslx/config
	if [ -n "${SLX_EXAM}" ]; then
		SLX_SCREEN_SAVER_GRACE_TIME=
	fi
	if [ -z "$SLX_SCREEN_SAVER_GRACE_TIME" ]; then
		GRACE="99:00:00"
		AUTOLOCK=False
	else
		GRACE="$( secsToTime "$SLX_SCREEN_SAVER_GRACE_TIME" )"
	fi
	if ! [ -s "$HOME/.xscreensaver" ]; then
		cat > "$HOME/.xscreensaver" <<EOF
mode:         one
cycle:        99:00:00
timeout:      99:00:00
lock:         $AUTOLOCK
lockTimeout:  $GRACE
fade:         False
unfade:       False
dpmsFullThrottle: True
newLoginCommand:
externalUngrabCommand: /opt/openslx/xscreensaver/ungrab
programs:     /opt/openslx/bin/bwlp-screensaver
selected:     0
EOF
	fi
	xscreensaver -no-splash &
fi

true

