#!/bin/bash
# ^SOURCED, actually running in ash

. /opt/openslx/config

# creates managed policy file, those settings cannot be changed by the user
# (if he even gets to the settings dialog in the first place)
create_chromium_policies() {
	if [ -n "$SLX_BROWSER_BOOKMARKS" ]; then
		bookmarkbar=true
	else
		bookmarkbar=false
	fi

	cat <<- EOF > "/etc/chromium-browser/policies/managed/kiosk-mode.json"
	{
		"AutoFillEnabled": false,
		"BackgroundModeEnabled": false,
		"BookmarkBarEnabled": $bookmarkbar,
		"DefaultBrowserSettingEnabled": true,
		"DeviceAutoUpdateDisabled": true,
		"DownloadRestrictions": 3,
		"HomepageLocation": "$SLX_BROWSER_URL",
		"NewTabPageLocation": "$SLX_BROWSER_URL",
		"PasswordManagerEnabled": false,
		"RestoreOnStartup": 4,
		"RestoreOnStartupURLs": "$SLX_BROWSER_URL",
		"ShowAppsShortcutInBookmarkBar": false,
		"TranslateEnabled": false
	}
	EOF
}

if [ "${PAM_SERVICE//autologin/}" != "$PAM_SERVICE" -a "$PAM_TTY" = ":0" ]; then
	create_chromium_policies
fi
true
