#######################################
# Include: Print Logo for console use #
#######################################

cat <<EOL
                                             __        __   
                .----.--.--.-----.___.--.--.|__|.----.|  |_ 
                |   _|  |  |     |___|  |  ||  ||   _||   _|
                |__| |_____|__|__|    \___/ |__||__|  |____|
          OpenSLX virtual machine environment preparation script ...

EOL
