#!/bin/bash

# Disable logout delay for demo user on shutdown/reboot/...
mkdir -p "/run/openslx"
touch "/run/openslx/demo-no-logout-delay"

for file in "$0".d/*; do
	[ -f "$file" ] || continue
	# hooks for browser-related stuff
	. "$file" || slxlog "kiosk-setup" "Failed to source '$file'."
done

exit 0
