#!/bin/bash
REQUIRED_MODULES="kernel"
# Use ||master even though it's the default branch, since this circumvents autoclone's shallow cloning,
# which breaks the version detection magic using git tags.
REQUIRED_GIT="https://git.openslx.org/dnbd3.git||master"
REQUIRED_BINARIES="
	dnbd3-fuse
	fusermount
	dnbd3-server
"
REQUIRED_DIRECTORIES="
"
