#!/bin/ash

if [ -n "$FIRMWARE" ] && [ "$SUBSYSTEM" = "firmware" ] && [ -n "$DEVPATH" ] && [ -e "/sys/$DEVPATH/data" ]; then
	echo "Kernel requests firmware $FIRMWARE" > "/dev/kmsg"
	printf "1" > "/sys/$DEVPATH/loading"
	if cat "/lib/firmware/$FIRMWARE" > "/sys/$DEVPATH/data" \
			|| cat "/lib/firmware/$(uname -r)/$FIRMWARE" > "/sys/$DEVPATH/data"; then
		printf "0" > "/sys/$DEVPATH/loading"
	else
		printf "%s" "-1" "/sys/$DEVPATH/loading"
	fi
fi

[ "$ACTION" != "add" ] && exit 0

[ -z "$MODALIAS" ] && exit 0

[ "${MODALIAS:0:5}" != "pci:v" ] && exit 0 # Ignore everything but PCI devices

ID="${MODALIAS:9:4}:${MODALIAS:18:4}"

LINE="$( lspci -n | grep -oEi "[0-9]{4}: $ID" | cut -c1-2 )"
[ "$LINE" = "03" ] && exit 0 # Skip GFX, handled by other module

modprobe "$MODALIAS"

