#!/bin/ash

. /opt/openslx/config

# Try to get fresh version from server
CONF=
if [ -n "$SLX_PVS_CONFIG_URL" ]; then
	DST="$(mktemp)"
	wget -T 5 -O "${DST}" "$SLX_PVS_CONFIG_URL"
	[ -s "${DST}" ] && CONF="--config=${DST}"
fi

# In case nobody else manages this
xset +dpms
xset dpms 120 120 120
# In case idle-daemon manages saver/dpms
[ -z "$HOME" ] && HOME="$( getent passwd "$(id -u)" | awk -F: '{print $6}' )"
touch "$HOME/.no-saver"

openbox &

timediff=5
counter=0

while [ $timediff -gt 3 ]; do
	start="$(date +%s)"
	/opt/openslx/bin/pvsmgr "$CONF" "$@"
	ret=$?
	[ "$ret" == "0" ] && break
	end="$(date +%s)"
	timediff=$(( end - start ))
	counter=$(( counter + 1 ))
	[ $counter -gt 8 ] && break
done

exit $ret

