#!/bin/ash

. /opt/openslx/config
DST="/opt/openslx/pvs2/pvs2.ini"

# Try to get fresh version from server
if [ -n "$SLX_PVS_CONFIG_URL" ]; then
	wget -T 10 -O "${DST}.new" "$SLX_PVS_CONFIG_URL"
	[ -s "${DST}.new" ] && mv -f "${DST}.new" "${DST}"
fi

exit 0

