#!/bin/ash

. /opt/openslx/config
[ -z "$SLX_PVS_CONFIG_URL" ] && exit 0
UUID=$( cat /run/system-uuid )
[ -z "$UUID" ] && exit 0

mkdir -p /etc/branding.d
exec curl -m 3 -o /etc/branding.d/50-roomplan.svg "${SLX_PVS_CONFIG_URL}&show=svg&machineuuid=${UUID}"
