#!/bin/ash
#
# This hook evaluates the SLX_VM_SOUND configuration option
# and mutes the sound via PulseAudio if appropriate. This will only
# take effect in non-virtual sessions (determined by the
# env variable SESSION_TYPE given by vmchooser).

if [ "$SESSION_TYPE" = "XSESSION" ]; then
	. /opt/openslx/config

	if [ "$SLX_VM_SOUND" = "DEFAULT_MUTED" ] || [ "$SLX_VM_SOUND" = "FORCE_MUTED" ]; then
		pactl set-sink-mute @DEFAULT_SINK@ 1
	fi
fi
: # fake success to not trigger slxlog
