#!/bin/ash

flag="/run/network/primary-dhcp.flag"
readonly flag
w=0

# Wait a maximum of 10 seconds for the flag file
while ! [ -e "$flag" ] && [ "$w" -lt 10 ]; do
	let w++
	sleep 1
done

# Then touch it anyways, this will prevent the DHCP
# trigger script from changing the hostname later on
mkdir -p /run/network
touch "$flag"

exit 0
